# Note: conda dependencies have only 1 "="
#       pip dependencies have 2 "=="
# Fuse pip dependencies together under one " - pip" item
#       Otherwise, only some of them are installed, because conda creates a temporary requirements.txt file
#       only the last -pip section

name: modnet

channels:
  - pytorch
  - conda-forge
  - nvidia/label/cuda-11.8.0

dependencies:
  - python=3.8
  - pip
#  - jupyterlab

  - pytorch
  - pytorch-cuda=11.8
  - torchvision

  - pip:
    # All pip dependencies